FROM registry.cn-shanghai.aliyuncs.com/yingzhuo/java:jre-8

LABEL MAINTAINER="应卓 <yingzhor@gmail.com>"

USER root:root

WORKDIR /opt/

COPY ./docker-entrypoint.sh /bin/entrypoint

RUN chmod a+x /bin/entrypoint && \
    mkdir -p /opt/data/ && \
    mkdir -p /opt/tmp/ && \
    mkdir -p /opt/log/ && \
    mkdir -p /opt/lib/ && \
    mkdir -p /opt/config/ && \
    mkdir -p /opt/k8s-probe/ && \
    mkdir -p /opt/k8s-config-map/ && \
    rm -rf /var/log && \
    ln -sf /opt/log/ /var/log

ENV APP_DEBUG=false

VOLUME /opt/ \
       /opt/data \
       /opt/tmp \
       /opt/log \
       /opt/lib \
       /opt/config \
       /opt/k8s-probe \
       /opt/k8s-config-map

STOPSIGNAL 15

ONBUILD COPY --chown=root:root *.jar /opt/app.jar

ONBUILD COPY --chown=root:root .configkeep *.conf *.yaml *.yml *.json *.properties *.xml *.toml *.ini *.groovy *.cnf *.cfg /opt/config/

ENTRYPOINT ["entrypoint"]
