FROM registry.cn-shanghai.aliyuncs.com/yingzhuo/java:8

MAINTAINER 应卓 <yingzhor@gmail.com>

RUN addgroup -S spring && adduser -S spring -G spring

COPY --chown=spring:spring ./docker-entrypoint.sh /home/spring/entrypoint.sh

RUN chmod +x /home/spring/entrypoint.sh && \
    mkdir -p /home/spring/data/ && \
    mkdir -p /home/spring/tmp/ && \
    mkdir -p /home/spring/log/ && \
    mkdir -p /home/spring/lib/ && \
    mkdir -p /home/spring/probe/ && \
    mkdir -p /home/spring/config && \
    chown -R spring:spring /home/spring

ENV SPRINGBOOT_HOME=/home/spring \
    SPRINGBOOT_LOG_DIR=/home/spring/log \
    SPRINGBOOT_DATA_DIR=/home/spring/data \
    SPRINGBOOT_TMP_DIR=/home/spring/tmp \
    SPRINGBOOT_LIB_DIR=/home/spring/lib \
    SPRINGBOOT_PROBE_DIR=/home/spring/probe \
    SPRINGBOOT_CONFIG_DIR=/home/spring/config \
    PATH=$PATH:${SPRINGBOOT_HOME} \
    APP_DEBUG=false

VOLUME /home/spring

STOPSIGNAL 15

ONBUILD COPY --chown=spring:spring *.jar /home/spring/app.jar

ONBUILD COPY --chown=spring:spring .configkeep *.conf *.yaml *.yml *.json *.properties *.xml *.toml *.ini *.groovy *.cnf *.cfg /home/spring/config/

WORKDIR /home/spring

USER spring

CMD ["entrypoint.sh"]