FROM registry.cn-shanghai.aliyuncs.com/yingzhuo/java:8

LABEL MAINTAINER="应卓 yingzhor@gmail.com"

RUN addgroup -S spring && \
    adduser -S spring -G spring

COPY --chown=spring:spring ./docker-entrypoint.sh /bin/entrypoint.sh

RUN chmod a+x /bin/entrypoint.sh && \
    mkdir -p /home/spring/data/ && \
    mkdir -p /home/spring/tmp/ && \
    mkdir -p /home/spring/log/ && \
    mkdir -p /home/spring/lib/ && \
    mkdir -p /home/spring/probe/ && \
    mkdir -p /home/spring/config && \
    chown -R spring:spring /home/spring

ENV APP_DEBUG=false

VOLUME /home/spring/data \
       /home/spring/tmp \
       /home/spring/log \
       /home/spring/lib \
       /home/spring/probe \
       /home/spring/config

STOPSIGNAL 15

ONBUILD COPY --chown=spring:spring *.jar /home/spring/app.jar

ONBUILD COPY --chown=spring:spring .configkeep *.conf *.yaml *.yml *.json *.properties *.xml *.toml *.ini *.groovy *.cnf *.cfg /home/spring/config/

WORKDIR /home/spring

USER spring

ENTRYPOINT ["entrypoint.sh"]